[tool.ruff]
select = [
    "E", # pycodestyle
    "F", # pyflakes
    "W", # 
]

exclude = [
    # excluding by default
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",

    # our own exclusions
    "notebooks",
    "venv",
]

ignore = ["E402"]
line-length = 160

[tool.isort]
skip = [
    "notebooks",
    "venv",
    ".venv",
]

# Sort imports alphabetically
force_sort_within_sections=true
lexicographical=true
single_line_exclusions=['typing']
order_by_type=false
group_by_package=true

# Make it compatible with black
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

# Set the line length
line_length=160

[tool.black]
line-length = 160

# force-exclude for the pre-commit hook
force-exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | venv
  | _build
  | buck-out
  | build
  | dist
  | notebooks
  | data
  | .venv
)/
'''


[tool.pytest.ini_options]
pythonpath = "."
